apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: pipelinerun-with-sbom-external-task
spec:
  pipelineSpec:
    tasks:
      - name: sbom-task-external-link
        taskRef:
          name: sbom-task-external-link
    results:
    - name: IMAGE_URL
      description:  Contains the SBOM link
      value: $(tasks.sbom-task-external-link.results.LINK_TO_SBOM)
